name: app_1gochat
description: A chat Application for Merch App Users.
publish_to: 'none'
version: 2023.12.21

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  amplify_analytics_pinpoint: ^1.6.0
  amplify_api: ^1.6.0
  amplify_auth_cognito: ^1.6.0
  amplify_authenticator: ^1.5.1
  amplify_datastore: ^1.6.0
  amplify_flutter: ^1.6.0
  amplify_storage_s3: ^1.6.0
  chewie: ^1.7.4
  async: ^2.11.0
  cached_network_image: ^3.3.0
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  flutter_timezone: ^1.0.7
  fluttertoast: ^8.2.4
  http: ^1.1.2
  intl: ^0.18.0
  mime: ^1.0.4
  multiple_stream_builder: ^3.0.2
  ntp: ^2.0.0
  permission_handler: ^11.1.0
  receive_intent: ^0.2.4
  shimmer: ^3.0.0
  timezone: ^0.9.2
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - "assets/images/splash.png"
